//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo1
    {
        public int Modelo1Id { get; set; }
        public int nombre { get; set; }
        public int cargo { get; set; }
        public int Modelo2Id { get; set; }
    
        public virtual Modelo2 Modelo2 { get; set; }
    }
}
